### ISSUE TITLE
Race condition when using runExclusively

### ISSUE THREAD

**Issue by trajano** [DirtyHairy/async-mutex#44]
I have the runExclusively code and the acquire method and I found that the runExclusively sometimes misses the lock at least on android.

![image](https://user-images.githubusercontent.com/110627/125009681-006c8d00-e033-11eb-8cca-4c1b7906e031.png)

Here's a snack that you can use to test it out.  It's very random.

https://snack.expo.io/@trajano/sqlite-transaction-block

But so far I haven't been able to do it on the acquire. release style.

**Comment by DirtyHairy** [comment]
HI @trajano !

Sorry, I don't seem to be able to access the console in the virtual devices linked in the snack. However, I see two problems with your code:

1. You create a new instance of the mutex each time the component renders. Thus, a rerender between calls to your handlers will create a new mutex, and the async code in the handlers can interleave. You should either wrap the mutex in `useRef` or use a module-global instance.
2. You execute `await mutex.lock()` before your call to `mutex.runExclusive()` and never release the lock. This means that the mutex stays locked, and the code wrapped in `runExclusive` never executes. This consistent with your log messages, which seem to originate from `startMutexTxn()` (and not `startMutexTxn2`).

**Comment by trajano** [comment]
Thanks let me fix it I think it was a left over copy and paste.

**Comment by DirtyHairy** [comment]
Thanks for the pointer to the console, hiding in plain sight. I can observe the same phenomenon in the log as you, so it superficially looks like the lock is not taking effect, but look what happens after adding a timestamp to the log:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/2444224/125055150-351a2c00-e0a7-11eb-971d-dd4d9ea0989d.png">

(the timestamp is the second number, the first one is an instance ID that I added to the mutex in order to make sure that this is not some weird effect of hot reloading). Both logs a separated by ~2000 msec, as expected. This is just an output issue, it seems that the console sometimes misses updates.
